#
# NOTE: Our Voice USA has a Neo4j Enterprise License for development. Only use
#       this Dockerfile if you do as well.
#

FROM neo4j:3.5.1-enterprise

ADD https://github.com/neo4j-contrib/spatial/releases/download/0.25.7-neo4j-3.4.9/neo4j-spatial-0.25.7-neo4j-3.4.9-server-plugin.jar /var/lib/neo4j/plugins/
ADD https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.5.0.1/apoc-3.5.0.1-all.jar /var/lib/neo4j/plugins/

