import {
  FaCog as Cog,
  FaClipboard as Clipboard,
  FaSquare as Dash,
  FaDonate as Donate,
  FaFacebook as Facebook,
  FaTwitter as Twitter,
  FaGlobe as Globe,
  FaGithub as GitHub,
  FaYoutube as YouTube,
  FaInfo as Info,
  FaMap as Map,
  FaBars as Menu,
  FaPaperclip as Paperclip,
  FaUser as Person,
  FaPhone as Phone,
  FaQuestionCircle as Question,
  FaStar as Rate,
  FaBriefcase as Queue,
  FaQrcode as QRCode,
  FaUpload as Upload,
} from 'react-icons/fa';

export {
  Cog,
  Clipboard,
  Dash,
  Donate,
  Facebook,
  Twitter,
  Globe,
  GitHub,
  YouTube,
  Info,
  Map,
  Menu,
  Paperclip,
  Person,
  Phone,
  Question,
  Rate,
  Queue,
  QRCode,
  Upload,
};
